### ISSUE TITLE
已配置好数据库，但是数据无法在folia正常读取

### ISSUE THREAD

**Issue by xiaoluofa** [blank038/NyEconomy#1]
![image](https://github.com/blank038/NyEconomy/assets/75927411/43e77865-6651-4cb3-bfcc-76a7f1fe6fd3)
![image](https://github.com/blank038/NyEconomy/assets/75927411/ba5e07d6-1e5f-4232-b24e-19da210b21a0)
红框内容才是，playerpoint还没支持folia

**Comment by blank038** [comment]
![{60A6B3D7-07AD-40ef-8063-D62E477F1578}](https://github.com/blank038/NyEconomy/assets/30598468/5f0abfaa-8042-4922-86fe-8352b1426cdf)

推送了一个 `1.7.1-SNAPSHOT` 版本用于修复 Folia 玩家登录时拉取缓存错误
你可以尝试更新到这个版本后试试看，如果还有问题可以尝试下面的步骤

如果你 MySQL 模式下无法正常显示，可能是因为编码问题，默认配置不自带编码参数
你可以在 config.yml 的 `data-option.url` 拼接上 `&useUnicode=true&characterEncoding=utf-8`
然后关闭服务器，在 MySQL 中删除表 `ny_economy` `ny_economy_option` `ny_economy_top` 并开启服务器让插件重新生成表

**Comment by xiaoluofa** [comment]
我觉得不是这个的问题，数据可以读取到了，但是nye me不行，而look可以。
我更新了插件没有用。需要删数据库吗，可是我里面已经有很多数据了，删除后导入数据？
![image](https://github.com/blank038/NyEconomy/assets/75927411/4cb01da6-466f-4f77-b16e-19c5e06ab95a)

**Comment by blank038** [comment]
> 我觉得不是这个的问题，数据可以读取到了，但是nye me不行，而look可以。 我更新了插件没有用。需要删数据库吗，可是我里面已经有很多数据了，删除后导入数据？ ![image](https://private-user-images.githubusercontent.com/75927411/318166229-4cb01da6-466f-4f77-b16e-19c5e06ab95a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzIyNDIsIm5iZiI6MTcxMTc3MTk0MiwicGF0aCI6Ii83NTkyNzQxMS8zMTgxNjYyMjktNGNiMDFkYTYtNDY2Zi00Zjc3LWIxNmUtMTljNWUwNmFiOTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA0MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMmU4ODNiMDIyZmZkNTA3NjkxMjlmNzk3MjM5NzZhNjhhYjA0MDc1Yjk5N2YwZTk0YWU5MTVhM2RjNjVjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAtdssu0NzNwTlIxZpv6NIdBpYOI08lXTkIV7Gjy6oU)

是否已经更新到 NyEconomy-1.7.1-SNAPSHOT 与 AyCore-1.1.0-BETA 了呢？

**Comment by xiaoluofa** [comment]
> > 我觉得不是这个的问题，数据可以读取到了，但是nye me不行，而look可以。 我更新了插件没有用。需要删数据库吗，可是我里面已经有很多数据了，删除后导入数据？ ![image](https://private-user-images.githubusercontent.com/75927411/318166229-4cb01da6-466f-4f77-b16e-19c5e06ab95a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3NzIyNDIsIm5iZiI6MTcxMTc3MTk0MiwicGF0aCI6Ii83NTkyNzQxMS8zMTgxNjYyMjktNGNiMDFkYTYtNDY2Zi00Zjc3LWIxNmUtMTljNWUwNmFiOTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA0MTIyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVhMmU4ODNiMDIyZmZkNTA3NjkxMjlmNzk3MjM5NzZhNjhhYjA0MDc1Yjk5N2YwZTk0YWU5MTVhM2RjNjVjYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EAtdssu0NzNwTlIxZpv6NIdBpYOI08lXTkIV7Gjy6oU)
> 
> 是否已经更新到 NyEconomy-1.7.1-SNAPSHOT 与 AyCore-1.1.0-BETA 了呢？

是

**Comment by xiaoluofa** [comment]
![image](https://github.com/blank038/NyEconomy/assets/75927411/3d3e06a9-b242-4100-96fa-bb244dfdd30c)

**Comment by blank038** [comment]
1. 能否给我查看一下 /nye me 的效果是什么样？
2. 查看一下日志文件是否有关于 NyEconomy 相关的报错(加载时、启动时、运行时)
3. 是否在 config.yml 中启用了货币
4. 手动输入 /papi parse me %nyeconomy_货币名% 输出的是什么？
5. 使用 NyEconomy 自带的商店消耗 NyEconomy 货币购买是否正常？

劳烦提供一下这些信息，谢谢。

**Comment by xiaoluofa** [comment]
首先上面的截图

**Comment by xiaoluofa** [comment]
重启后paper正常。
